### PR TITLE
added support of Reshaper InspectCode command line tool

### PR DESCRIPTION
**Pull request by rjasica**
added support of Reshaper InspectCode command line tool
http://www.jetbrains.com/resharper/features/command-line.html

### CODE REVIEW

**Comment by mycroes** [comment]
Did anyone notice that it's actually called ReSha**r**per (notice the r)?

**Comment by rjasica** [comment]
Good catch!

@uhafner Do you know if we can change this typo without breaking backward compatibility?

**Comment by uhafner** [comment]
I think that I already changed the UI representation and the classes after merging the PR. 

Or did I forget something?

**Comment by rvanrosmalen** [comment]
Trying to get this working with the 2017.3.3 command line tools. The tool does not output warinings but writes everything to an xml file. Is this supported (and if so what should the name of the output file be)?

**Comment by uhafner** [comment]
The parser is an XML parser so it should work if the file format is still the same. You can try the format on your own: 

1. Clone the project https://github.com/jenkinsci/analysis-model
2. Write the file to the test resources folder
3. Add a new test case in ResharperInspectCodeAdapterTest

**Comment by rvanrosmalen** [comment]
Thanks for the reply. Where does the plugin expect the XML file and how should it be named?  I have to supply the output file (mandatory now) to inspectcode and it is written but the plugin does not pick it up (and I cannot configure it as far as I can see).

**Comment by uhafner** [comment]
The name and path needs to be configured. In Freestyle projects in the UI, in pipelines using the pattern parameter.

**Comment by rvanrosmalen** [comment]
Ah I see it now.. I completely overlooked I had to configure both warnings and the workspace file scanner. Sorry! It is working now (with the latest ReSharper command line tools 2017.3.3). Thanks for helping me out.

**Pull request merged**
